import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import React, { useState } from "react";
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'
export default function App() {
  const router = useRouter()

  const [query, setQuery] = useState({
    name: "",
    email: ""
  });

  // Update inputs value
  const handleParam = () => (e) => {
    const name = e.target.name;
    const value = e.target.value;
    setQuery((prevState) => ({
      ...prevState,
      [name]: value
    }));
  };
  // Form Submit function
  const formSubmit = (e) => {
    e.preventDefault();
    console.log(query.name)
    console.log(query.password)
    // username=query.name
    // email=query.email
     if (query.name == "admin" && query.password == "password") 
     {
       alert("Submitted")
     router.push('/posts/first')
     }
     else
     {
       alert("Try again")
     }
    const formData = new FormData();
    Object.entries(query).forEach(([key, value]) => {
      formData.append(key, value);
    });
    console.log(formData);
    
    // fetch("https://getform.io/{your-form-endpoint}", {
    //   method: "POST",
    //   body: formData
    // }).then(() => setQuery({ name: "", email: "", message: "" }));
  };
  return (
     <main className={styles.main}>
    <div className="App" className="styles.m-t">
      <h1>Login to our portal</h1>
      <form onSubmit={formSubmit}>
        <div>
          <label>Name</label>
          <input
            type="text"
            name="name"
            required
            placeholder="Name"
            className="form-control"
            value={query.name}
            onChange={handleParam()}
          />
        </div>
        <br></br>
        <div>
          <label>Password</label>
          <input
            type="password"
            name="password"
            required
            placeholder="Password"
            className="form-control"
            value={query.password}
            onChange={handleParam()}
          />
        </div>
         <br></br>
       
        <button type="submit" className="styles.btn btn-primary block full-width m-b login">Submit</button>
      </form>
    </div>
    </main>
  );
}
// import styles from '../styles/animate.css'


// export default function Home() {
//   function doSomething() {
   
//     if (($('#username').val()=="")) {
// 		alert('Please Enter Username');
// 		} else if (($('#password').val()=="")) {
// 		alert('Please Enter valid Password');

// 		} else {
//       alert("Submitted");
//     }
//  // do something here
  
// }
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//       <div className="styles.gray-bg">
//         <div className="styles.middle-box text-center loginscreen animated fadeInDown">
//             <div>
//                 {/* <div>
//                     <h1 className="logo-name"><img src="images/e-voting-logo.png" width="150"></h1>
//                 </div> */}
//                 <h3>Welcome to Aadhaar-Voting</h3>
                
                
//                 <div className="styles.m-t" role="form" action="#">
//                     <div className="form-group">
//                          <input type="text" id="username" name="username"  className={errors.email && touched.email && "error"} placeholder="Username" required autofocus></input>
//                         {errors.email && touched.email && (<div className="input-feedback">{errors.email}</div>
//                         )}
//                     </div>
//                     <div className="form-group">
//                         <input type="password" name="password" id="password" className="styles.form-control" placeholder="Password" required></input>
//                     </div>
//                     <button id="login" className="styles.btn btn-primary block full-width m-b login" onClick={doSomething}>Login</button>
                    
//                 </div>
//                 <br></br>
//                 <div id="messagebox" className="alert alert-danger fade in">
//                   <a href="" className="close" data-dismiss="alert">&times;</a>
//                   <strong id="errormsg">Error!</strong> 
//                 </div>
//             </div>
//         </div>
//         </div>
//         {/* <h1 className={styles.title}>
//           Welcome me to <a href="https://nextjs.org">Next.js!</a>
//         </h1> */}
//         {/* <h1 className="title">
//         Read{' '}
//         <Link href="/posts/first">
//         <a>this page!</a>
//         </Link>
//         </h1>
//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/master/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div> */}
//       </main>

//       <footer className={styles.footer}>
//       </footer>
//     </div>
//   )
// }
